// SPDX-License-Identifier: GPL-2.0-or-later
#include "FieldRangeResolver.h"
#include <algorithm>
namespace pv
{
void FieldRangeResolver::resolve(Field& f, const QVector<DataSource>& sources)
{
    f.ranges.clear();
    f.exact = false;
    f.wireBacked = false;
    f.derived = f.generated;
    if (f.generated) {
        f.rangeNote = "Generated by Wireshark; no direct wire range";
        return;
    }
    if (f.source < 0 || f.source >= sources.size()) {
        f.rangeNote = "Data-source mapping unavailable";
        return;
    }
    const auto& s = sources[f.source];
    if (f.length > UINT32_MAX || s.captured > UINT32_MAX) {
        f.rangeNote = "Range exceeds supported Wireshark bounds";
        return;
    }
    f.derived = !s.currentFrame;
    if (f.start >= s.captured || !f.length) {
        f.rangeNote = "No captured bytes in reported field range";
        return;
    }
    const uint64_t available = std::min<uint64_t>(f.length, s.captured - f.start);
    f.clipped = available != f.length;
    auto add = [&](uint64_t bit, uint64_t length) {
        const auto limit = s.captured * 8;
        if (bit >= limit) {
            f.clipped = true;
            return;
        }
        length = std::min(length, limit - bit);
        if (length)
            f.ranges.push_back({ bit, length });
    };
    if (f.mask) {
        if (f.length > 8) {
            f.rangeNote = "Mask byte order or container mapping unavailable";
            return;
        }
        // Numeric significance to MSB-first bit coordinates, independently for each set bit.
        for (unsigned b = 0; b < 64; ++b) {
            if (!(f.mask & (uint64_t(1) << b)))
                continue;
            if (b >= f.length * 8) {
                f.rangeNote = "Mask exceeds field container";
                f.ranges.clear();
                return;
            }
            if (!f.littleEndian && !f.bigEndian && f.length > 1) {
                // add_bitmask_value may omit endian flags. Its explicit MSB-first
                // offset/size still locates the registered mask span (e.g. VLAN).
                unsigned highest = 63;
                while (!(f.mask & (uint64_t(1) << highest)))
                    --highest;
                if (!f.bitSize || uint64_t(f.bitOffset) + f.bitSize > f.length * 8) {
                    f.rangeNote = "Mask byte order or explicit bit mapping unavailable";
                    f.ranges.clear();
                    return;
                }
                add(f.start * 8 + f.bitOffset + highest - b, 1);
            } else {
                const auto byte = f.littleEndian ? b / 8 : f.length - 1 - b / 8;
                add((f.start + byte) * 8 + 7 - b % 8, 1);
            }
        }
    } else {
        // Metadata describes a source range; no width is inferred from display text.
        const uint64_t width = f.bitSize ? f.bitSize : f.length * 8;
        const uint64_t offset = f.bitSize ? f.bitOffset : 0;
        if (offset + width > f.length * 8) {
            f.rangeNote = "Bit metadata exceeds field container";
            return;
        }
        add(f.start * 8 + offset, width);
    }
    std::sort(f.ranges.begin(), f.ranges.end(), [](auto a, auto b) { return a.start < b.start; });
    QVector<BitRange> merged;
    for (const auto r : f.ranges) {
        if (!merged.empty() && merged.back().end() == r.start)
            merged.back().length += r.length;
        else
            merged.push_back(r);
    }
    f.ranges = std::move(merged);
    f.exact = !f.clipped;
    f.wireBacked = s.currentFrame && !f.ranges.empty();
    f.rangeNote = f.clipped ? "Range clipped to captured data; missing bytes omitted"
                            : (s.currentFrame ? "Wireshark field range in current frame"
                                              : "Separate data source; no current-frame mapping");
    if (!f.mask && !f.bitSize && f.length)
        f.rangeNote += "; byte container shown, finer bit occupancy not separately exposed";
}
}
